### ISSUE TITLE
Cannot import name "all_tasks"

### ISSUE THREAD

**Issue by joydragon** [koromodako/mkctf#12]
Congratulations on the v6.0.0. I've just cloned the repo today and I got an issue.
After running the setup script it seems that everything is fine, but then when I try to run mkctf-cli I get the following error:
![imagen](https://user-images.githubusercontent.com/4154219/57577480-d2389600-7445-11e9-82c2-7cd63214a7ee.png)

I'm not that great on python, where can I modify the code to get the import right?
Thanks in advance

**Comment by joydragon** [comment]
Got the problem for this issue, you should have installed python 3.7. Can you please update the Readme?

"This project has been design to run in a Linux environment having Python 3.6+ support."

Thanks

**Comment by koromodako** [comment]
Right sorry I'm updating it right away.
