### ISSUE TITLE
mkctf-cli: command not found

### ISSUE THREAD

**Issue by malysn** [koromodako/mkctf#13]
Followed installation instructions to the tee and added ~/bin to $PATH. Installation of mkctf along with all dependencies installed without errors. 

Issue: 
- mkctf-cli command not found
- mkctf-* appears to be a broken link

![Broken Link](https://user-images.githubusercontent.com/25220748/121481100-5e8b5d80-c9fe-11eb-96d9-a4ae04748a80.PNG)

**Comment by koromodako** [comment]
Thank you! Just fixed a small but important typo in the README.md ([see this commit](https://github.com/koromodako/mkctf/commit/0f47c5f43648bb5cf94008a670b39597dba45a31)).

Tell me if it solves your problem.

Regards

**Comment by malysn** [comment]
Yep, its working now. Thanks!
