### ISSUE TITLE
Invalid Repository Configuration - missing key: .name

### ISSUE THREAD

**Issue by malysn** [koromodako/mkctf#14]
Command: mkctf-cli init
Error: [mkctf]( WARNING)> invalid repository configuration - missing key: .name
[mkctf](CRITICAL)> critical error: repository configuration is missing or invalid.

I went through the configuration files, not sure what to look for. I've tried matching the repo_dir to match /root/mkctf-cli as well. 

![repository configuration is missing or invalid](https://user-images.githubusercontent.com/25220748/121801978-b62f0080-cc6c-11eb-9b0f-9dd2fb93315e.PNG)

**Comment by koromodako** [comment]
Hey @Cookedbeefchops !

This [commit](https://github.com/koromodako/mkctf/commit/3cac3a55465cf78450f1616762ba96ed699f0001) may fix this issue !

Give it another try and keep me updated

Regards

**Comment by malysn** [comment]
Issue is fixed. Thanks!
