### ISSUE TITLE
[Request] Support user categories

### ISSUE THREAD

**Issue by noraj** [koromodako/mkctf#3]
Here are the current categories, in the future you may want to add user choice support.

For example the user write the category he want in the config file or if non provided default one are used.

```
	0 - bugbounty
	1 - crypto
	2 - forensics
	3 - misc
	4 - programming
	5 - pwn
	6 - reverse
	7 - web
```

**Comment by koromodako** [comment]
This feature is to be implemented. Feel free to fork the repo and implement it.
For now you can edit the first lines of [functions.py](https://github.com/pdautry/py_chall_factory/blob/master/core/functions.py) if you want to customize categories.

Thank you for your feedback.
