### ISSUE TITLE
This is not a CTF framework

### ISSUE THREAD

**Issue by noraj** [koromodako/mkctf#5]
You tool is not a CTF framework. This tool just create some empty file and folder, there is no server front-end/back-end, score-board, account registration and login, etc...

You please remove the `ctf-framework` tag.

**Comment by koromodako** [comment]
This repository comes with [inshack-2017](https://github.com/HugoDelval/inshack-2017) and helps to manage CTF-related files. It creates folders following a template which helps automating deployment and other scripting-related things.

*Why this tag appears on this repository ?*
I fully agree this is just a tool but it has been made to manage files for `ctf-framework`s. The tag does not mean the exact content of a repository but also **semantic relationship**.

I'm glad you're interested in this repo.

**Comment by noraj** [comment]
So please add a link to https://github.com/HugoDelval/inshack-2017 in the README. That's not obvious.
